DROP TABLE `photo`;

CREATE TABLE `photo` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `id` mediumint,
  `name` TEXT default NULL,
  `comment` TEXT default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `photo` (`id`,`name`,`comment`) VALUES (1,"nec mauris","Morbi quis urna. Nunc quis"),(2,"nec mauris","quam"),(3,"urna","accumsan sed, facilisis"),(4,"congue a, aliquet","placerat, orci lacus"),(5,"in, tempus eu,","adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus"),(6,"Donec","neque sed"),(7,"elit. Nulla","bibendum ullamcorper. Duis cursus,"),(8,"nec, diam.","est, congue a, aliquet vel, vulputate eu, odio. Phasellus"),(9,"neque","mollis lectus pede et risus."),(10,"magnis","Cum sociis natoque");
INSERT INTO `photo` (`id`,`name`,`comment`) VALUES (11,"elit.","porttitor tellus"),(12,"conubia","auctor odio a purus. Duis"),(13,"placerat, orci lacus","Nunc mauris"),(14,"sapien, cursus in,","ut"),(15,"fermentum metus.","ac urna. Ut tincidunt vehicula"),(16,"turpis nec mauris","egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta"),(17,"orci. Phasellus dapibus","ac orci. Ut semper pretium"),(18,"eu arcu. Morbi","magnis"),(19,"neque et nunc.","Curabitur egestas nunc sed libero. Proin"),(20,"Suspendisse","commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque");
INSERT INTO `photo` (`id`,`name`,`comment`) VALUES (21,"non arcu. Vivamus","ultrices."),(22,"magnis dis","rutrum, justo. Praesent luctus. Curabitur egestas nunc sed"),(23,"Nulla","pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque"),(24,"eu enim. Etiam","sagittis. Nullam"),(25,"Nullam","nec enim."),(26,"mus.","convallis convallis dolor."),(27,"tempus mauris","quis turpis vitae purus gravida sagittis."),(28,"tempus","Sed dictum. Proin eget"),(29,"malesuada.","vel lectus. Cum"),(30,"malesuada","nunc nulla vulputate dui,");
INSERT INTO `photo` (`id`,`name`,`comment`) VALUES (31,"a, magna.","cubilia Curae; Donec"),(32,"adipiscing.","nec urna et arcu imperdiet ullamcorper. Duis at lacus."),(33,"nec","consequat"),(34,"eu dui.","ipsum."),(35,"lacus","porta elit, a feugiat tellus lorem eu metus."),(36,"non, vestibulum","tincidunt nibh. Phasellus"),(37,"ac","facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate,"),(38,"Vestibulum ut eros","facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec"),(39,"ac, feugiat","nisi. Mauris nulla. Integer urna. Vivamus molestie"),(40,"fermentum","sem egestas blandit. Nam nulla magna, malesuada vel,");
INSERT INTO `photo` (`id`,`name`,`comment`) VALUES (41,"vel quam dignissim","ornare, elit elit fermentum"),(42,"erat, in consectetuer","sit"),(43,"vitae, sodales","odio. Phasellus at augue id ante dictum cursus."),(44,"eu lacus. Quisque","quis turpis vitae purus gravida sagittis. Duis gravida. Praesent"),(45,"malesuada","lobortis risus. In mi pede, nonummy ut, molestie in, tempus"),(46,"ipsum.","non sapien molestie orci tincidunt adipiscing. Mauris molestie"),(47,"ipsum.","Ut semper pretium neque. Morbi quis urna."),(48,"Cum","sit"),(49,"non nisi.","molestie"),(50,"in, tempus eu,","erat, eget tincidunt dui augue");
INSERT INTO `photo` (`id`,`name`,`comment`) VALUES (51,"metus. Vivamus","dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus."),(52,"vitae,","tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet,"),(53,"enim consequat purus.","tellus faucibus leo, in lobortis tellus justo sit"),(54,"eu elit. Nulla","tincidunt, neque vitae semper egestas, urna"),(55,"quam.","lacinia. Sed congue, elit sed consequat auctor,"),(56,"vitae risus.","porttitor scelerisque neque."),(57,"Donec tempor, est","in aliquet lobortis, nisi nibh lacinia orci, consectetuer"),(58,"lectus","tincidunt. Donec"),(59,"eleifend nec, malesuada","nunc, ullamcorper eu, euismod ac, fermentum"),(60,"blandit","laoreet, libero");
INSERT INTO `photo` (`id`,`name`,`comment`) VALUES (61,"Curabitur","Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus"),(62,"nonummy","neque sed dictum eleifend, nunc risus varius"),(63,"pharetra. Nam ac","Nunc mauris"),(64,"pharetra. Nam","at, iaculis"),(65,"tristique","Cras eu"),(66,"ut, sem.","posuere cubilia Curae; Donec"),(67,"Aliquam rutrum lorem","vehicula. Pellentesque tincidunt tempus risus."),(68,"sagittis lobortis","Proin vel arcu eu odio tristique pharetra. Quisque ac"),(69,"lectus justo eu","venenatis a, magna."),(70,"condimentum","scelerisque");
INSERT INTO `photo` (`id`,`name`,`comment`) VALUES (71,"auctor odio","sed sem egestas blandit. Nam nulla magna, malesuada"),(72,"non,","dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus."),(73,"quam. Curabitur vel","vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue"),(74,"molestie orci tincidunt","a, auctor"),(75,"orci sem eget","tincidunt, neque"),(76,"Aliquam tincidunt,","risus. In mi pede, nonummy ut, molestie in, tempus"),(77,"Nunc","Vestibulum accumsan neque"),(78,"sem mollis dui,","arcu. Vestibulum ut eros non"),(79,"leo.","turpis vitae purus gravida sagittis. Duis gravida. Praesent"),(80,"gravida sit amet,","Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper");
INSERT INTO `photo` (`id`,`name`,`comment`) VALUES (81,"felis. Donec","Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra."),(82,"Curabitur","sapien"),(83,"Nulla interdum.","quis lectus. Nullam suscipit, est ac facilisis"),(84,"facilisis,","eget metus. In nec orci. Donec nibh. Quisque nonummy"),(85,"aptent","nec,"),(86,"metus eu","dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus"),(87,"semper","a nunc. In at"),(88,"ac tellus.","enim. Mauris"),(89,"Morbi non sapien","euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate"),(90,"dictum mi, ac","Cras eget nisi");
INSERT INTO `photo` (`id`,`name`,`comment`) VALUES (91,"tincidunt. Donec","amet risus. Donec egestas. Aliquam nec"),(92,"ante","sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer"),(93,"libero. Proin","metus urna convallis erat, eget tincidunt"),(94,"semper et,","ante ipsum primis in faucibus orci"),(95,"diam.","consectetuer, cursus et, magna."),(96,"est.","tortor."),(97,"elementum, dui","leo. Vivamus nibh dolor, nonummy ac,"),(98,"consequat purus. Maecenas","ante. Maecenas"),(99,"molestie arcu. Sed","blandit. Nam nulla magna, malesuada vel, convallis in, cursus"),(100,"Donec","massa. Quisque");
