DROP TABLE `piece_of_evidence`;

CREATE TABLE `piece_of_evidence` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `id` mediumint,
  `name` TEXT default NULL,
  `comment` TEXT default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `piece_of_evidence` (`id`,`name`,`comment`) VALUES (1,"posuere at, velit.","Donec luctus aliquet odio. Etiam ligula"),(2,"leo. Cras vehicula","erat semper"),(3,"orci, in","eu, ultrices sit amet, risus. Donec"),(4,"libero lacus,","arcu. Morbi sit amet"),(5,"tempor augue","libero dui"),(6,"interdum feugiat.","mattis. Cras"),(7,"tempor diam dictum","placerat, orci lacus vestibulum lorem, sit amet ultricies sem"),(8,"tempor","aliquet, metus urna convallis erat, eget tincidunt dui augue"),(9,"luctus felis","Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna."),(10,"ipsum.","posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse");
INSERT INTO `piece_of_evidence` (`id`,`name`,`comment`) VALUES (11,"ipsum","at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat,"),(12,"erat volutpat. Nulla","odio sagittis semper. Nam tempor"),(13,"elit,","molestie. Sed id risus quis diam luctus lobortis."),(14,"pellentesque, tellus","Proin eget odio. Aliquam vulputate ullamcorper"),(15,"tellus justo","amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing"),(16,"amet risus.","malesuada fames ac"),(17,"Nulla","risus, at"),(18,"Maecenas ornare","Integer tincidunt aliquam arcu. Aliquam"),(19,"Curabitur","iaculis enim,"),(20,"nunc ac","id risus quis diam luctus lobortis. Class aptent");
INSERT INTO `piece_of_evidence` (`id`,`name`,`comment`) VALUES (21,"volutpat ornare, facilisis","eget metus. In"),(22,"sit amet risus.","et libero. Proin mi."),(23,"ut, sem. Nulla","lobortis. Class aptent"),(24,"ultricies","lectus convallis est, vitae sodales"),(25,"Donec tempus, lorem","eget lacus. Mauris"),(26,"felis eget","arcu. Sed eu nibh vulputate mauris sagittis"),(27,"nisi","feugiat placerat velit. Quisque"),(28,"vestibulum, neque sed","sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales."),(29,"sem.","suscipit, est ac facilisis facilisis, magna tellus faucibus"),(30,"Nam tempor diam","sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem");
INSERT INTO `piece_of_evidence` (`id`,`name`,`comment`) VALUES (31,"dui.","feugiat metus"),(32,"euismod mauris","adipiscing, enim mi"),(33,"dolor.","Donec dignissim magna a tortor. Nunc commodo auctor velit."),(34,"ligula","in consequat enim"),(35,"cursus","mus. Donec dignissim magna"),(36,"Duis ac arcu.","Nam interdum"),(37,"urna. Ut","natoque penatibus et magnis"),(38,"vestibulum","neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed"),(39,"non enim. Mauris","augue porttitor interdum. Sed auctor odio a purus."),(40,"ultrices, mauris","eu nulla at sem molestie sodales. Mauris blandit");
INSERT INTO `piece_of_evidence` (`id`,`name`,`comment`) VALUES (41,"cursus luctus,","volutpat. Nulla facilisis. Suspendisse commodo"),(42,"Integer vulputate, risus","et arcu imperdiet ullamcorper. Duis"),(43,"Donec sollicitudin adipiscing","Duis volutpat nunc sit amet metus."),(44,"faucibus ut,","non magna."),(45,"mauris a nunc.","Fusce mollis. Duis sit amet"),(46,"sed, facilisis vitae,","lobortis risus. In"),(47,"netus et","sapien, gravida non, sollicitudin"),(48,"mi, ac mattis","magna."),(49,"nunc est, mollis","Donec"),(50,"sagittis lobortis","vitae erat vel pede blandit congue. In");
INSERT INTO `piece_of_evidence` (`id`,`name`,`comment`) VALUES (51,"urna. Nunc","tempus risus. Donec"),(52,"neque sed dictum","adipiscing non, luctus sit amet, faucibus ut, nulla. Cras"),(53,"Ut tincidunt orci","libero est,"),(54,"pede, malesuada vel,","Mauris blandit enim consequat purus."),(55,"sagittis. Duis","eu enim. Etiam imperdiet"),(56,"vitae odio","nec tellus. Nunc lectus pede, ultrices a, auctor"),(57,"ligula. Aliquam","congue a, aliquet"),(58,"fermentum","Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla"),(59,"fermentum","semper et, lacinia"),(60,"convallis","elit, dictum eu, eleifend");
INSERT INTO `piece_of_evidence` (`id`,`name`,`comment`) VALUES (61,"a tortor.","luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed"),(62,"a","metus. Aliquam"),(63,"penatibus","quam vel sapien imperdiet ornare. In faucibus. Morbi"),(64,"Mauris vestibulum, neque","mollis nec, cursus a, enim. Suspendisse"),(65,"habitant morbi","nibh. Quisque nonummy ipsum non arcu."),(66,"orci.","Fusce dolor quam, elementum at, egestas a, scelerisque"),(67,"eu, accumsan sed,","vel est tempor bibendum. Donec felis"),(68,"nec","lorem, vehicula et, rutrum eu, ultrices sit amet, risus."),(69,"Proin","Cras eu tellus"),(70,"facilisis. Suspendisse commodo","quam, elementum at, egestas a, scelerisque sed,");
INSERT INTO `piece_of_evidence` (`id`,`name`,`comment`) VALUES (71,"Etiam gravida","mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras"),(72,"Proin eget odio.","ac mattis velit"),(73,"dui.","tempus,"),(74,"magna sed","in sodales elit erat"),(75,"nec, imperdiet","Mauris quis"),(76,"ac","Suspendisse ac metus"),(77,"Proin","sollicitudin a, malesuada"),(78,"Etiam ligula tortor,","in consequat enim diam vel"),(79,"sed","felis. Nulla tempor augue ac ipsum. Phasellus"),(80,"diam dictum sapien.","gravida sit amet, dapibus id, blandit at,");
INSERT INTO `piece_of_evidence` (`id`,`name`,`comment`) VALUES (81,"arcu et pede.","lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet"),(82,"non justo.","aliquam eu, accumsan sed,"),(83,"bibendum ullamcorper. Duis","odio. Etiam"),(84,"Praesent luctus.","Nulla aliquet. Proin velit."),(85,"amet ornare","pretium aliquet, metus urna convallis erat, eget"),(86,"eu","Vivamus sit amet risus. Donec egestas."),(87,"blandit. Nam","elit. Curabitur"),(88,"aliquet,","mauris sagittis placerat. Cras dictum ultricies ligula. Nullam"),(89,"libero.","vel, vulputate"),(90,"Nunc sollicitudin","metus. In lorem. Donec elementum, lorem ut");
INSERT INTO `piece_of_evidence` (`id`,`name`,`comment`) VALUES (91,"massa non","aptent taciti sociosqu ad"),(92,"euismod","Nam ligula elit, pretium et, rutrum"),(93,"Integer eu","velit. Sed malesuada augue ut lacus."),(94,"iaculis","mollis. Duis sit amet diam"),(95,"Duis dignissim","leo. Morbi neque tellus, imperdiet non,"),(96,"convallis ligula. Donec","rhoncus id,"),(97,"nec","lobortis risus. In mi pede, nonummy"),(98,"lorem vitae","Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet."),(99,"ridiculus mus. Aenean","elementum sem, vitae aliquam eros turpis non enim. Mauris"),(100,"nisi.","arcu. Sed et libero. Proin mi. Aliquam");
