DROP TABLE `police_case`;

CREATE TABLE `police_case` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `id` mediumint,
  `name` varchar(255) default NULL,
  `comment` TEXT default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `police_case` (`id`,`name`,`comment`) VALUES (1,"voiture volée","mi, ac mattis velit justo nec"),(2,"agression","convallis erat, eget tincidunt dui augue"),(3,"raquette","nostra, per"),(4,"agression","venenatis a, magna. Lorem ipsum dolor sit amet,"),(5,"voiture volée","ipsum leo elementum sem, vitae aliquam eros turpis"),(6,"agression","non, bibendum sed,"),(7,"voiture volée","Sed eu nibh vulputate mauris sagittis placerat. Cras"),(8,"meurtre","id sapien."),(9,"braquage","erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor."),(10,"enlèvement","quis accumsan convallis, ante lectus convallis est, vitae sodales");
INSERT INTO `police_case` (`id`,`name`,`comment`) VALUES (11,"raquette","lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis"),(12,"objets trouvés","ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec"),(13,"meurtre","Quisque libero lacus, varius et,"),(14,"enlèvement","quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula."),(15,"raquette","est. Mauris eu turpis. Nulla aliquet. Proin"),(16,"agression","dolor, tempus non, lacinia at, iaculis quis,"),(17,"agression","Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi"),(18,"agression","justo sit amet nulla. Donec non justo."),(19,"enlèvement","odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa."),(20,"raquette","tortor at risus. Nunc ac sem ut");
INSERT INTO `police_case` (`id`,`name`,`comment`) VALUES (21,"braquage","id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer,"),(22,"braquage","lectus quis massa. Mauris vestibulum, neque sed dictum eleifend,"),(23,"meurtre","malesuada vel,"),(24,"enlèvement","Maecenas ornare egestas ligula. Nullam feugiat placerat"),(25,"raquette","sit amet orci. Ut"),(26,"enlèvement","Proin"),(27,"braquage","congue"),(28,"objets trouvés","risus. Nulla eget metus eu erat semper rutrum. Fusce dolor"),(29,"arme trouvé","aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim"),(30,"viol","vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque");
INSERT INTO `police_case` (`id`,`name`,`comment`) VALUES (31,"voiture volée","diam. Duis mi enim, condimentum"),(32,"agression","netus"),(33,"agression","odio sagittis semper. Nam tempor diam dictum sapien. Aenean"),(34,"voiture volée","sit amet massa. Quisque porttitor eros nec tellus."),(35,"meurtre","Phasellus"),(36,"raquette","Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero"),(37,"agression","libero dui"),(38,"braquage","vel est tempor bibendum. Donec felis orci,"),(39,"arme trouvé","id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis"),(40,"braquage","inceptos hymenaeos. Mauris ut quam vel sapien");
INSERT INTO `police_case` (`id`,`name`,`comment`) VALUES (41,"viol","cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut,"),(42,"meurtre","enim. Mauris"),(43,"viol","hendrerit consectetuer,"),(44,"viol","arcu et pede. Nunc sed orci lobortis augue"),(45,"raquette","ut, nulla. Cras eu"),(46,"objets trouvés","Class aptent taciti sociosqu"),(47,"arme trouvé","orci, consectetuer euismod est arcu ac orci."),(48,"viol","felis eget varius ultrices, mauris ipsum porta"),(49,"braquage","magna."),(50,"braquage","ipsum primis in faucibus orci");
INSERT INTO `police_case` (`id`,`name`,`comment`) VALUES (51,"enlèvement","et nunc."),(52,"raquette","eu, odio."),(53,"voiture volée","erat. Etiam vestibulum massa rutrum magna. Cras"),(54,"voiture volée","sapien, gravida non, sollicitudin a, malesuada"),(55,"raquette","dui, nec tempus mauris erat eget"),(56,"agression","aliquet vel, vulputate eu, odio. Phasellus at"),(57,"meurtre","metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec"),(58,"objets trouvés","id magna et ipsum cursus vestibulum."),(59,"agression","a nunc. In at pede. Cras vulputate"),(60,"viol","Proin vel arcu eu");
INSERT INTO `police_case` (`id`,`name`,`comment`) VALUES (61,"viol","vitae diam. Proin dolor. Nulla semper"),(62,"braquage","lacus. Mauris non"),(63,"braquage","arcu. Morbi sit"),(64,"arme trouvé","Curae;"),(65,"arme trouvé","Nullam nisl. Maecenas"),(66,"objets trouvés","a,"),(67,"meurtre","at arcu. Vestibulum ante ipsum"),(68,"voiture volée","Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum,"),(69,"arme trouvé","vel pede blandit congue. In scelerisque scelerisque dui."),(70,"braquage","lorem. Donec elementum,");
INSERT INTO `police_case` (`id`,`name`,`comment`) VALUES (71,"braquage","risus odio, auctor vitae, aliquet nec, imperdiet nec, leo."),(72,"viol","Phasellus in felis."),(73,"viol","quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper"),(74,"objets trouvés","eget"),(75,"raquette","Aliquam ornare, libero at auctor ullamcorper,"),(76,"arme trouvé","natoque"),(77,"braquage","egestas. Fusce aliquet magna a neque. Nullam ut nisi a"),(78,"braquage","in faucibus orci luctus et ultrices posuere"),(79,"braquage","feugiat. Sed nec metus facilisis"),(80,"braquage","purus gravida sagittis. Duis gravida. Praesent eu nulla at sem");
INSERT INTO `police_case` (`id`,`name`,`comment`) VALUES (81,"enlèvement","euismod et, commodo at, libero."),(82,"meurtre","Suspendisse dui. Fusce diam nunc, ullamcorper eu,"),(83,"meurtre","elementum, dui"),(84,"braquage","ornare. Fusce mollis. Duis sit amet diam eu dolor egestas"),(85,"voiture volée","diam. Sed"),(86,"raquette","lobortis"),(87,"agression","Cras vulputate velit eu sem. Pellentesque ut"),(88,"viol","ut, pharetra sed, hendrerit a,"),(89,"braquage","urna. Ut"),(90,"braquage","lectus ante dictum mi, ac mattis velit");
INSERT INTO `police_case` (`id`,`name`,`comment`) VALUES (91,"braquage","Integer vitae nibh. Donec est mauris,"),(92,"voiture volée","ullamcorper. Duis cursus, diam at pretium aliquet, metus"),(93,"objets trouvés","libero dui"),(94,"voiture volée","neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu"),(95,"arme trouvé","interdum ligula eu enim. Etiam imperdiet"),(96,"meurtre","magna"),(97,"raquette","laoreet, libero et tristique pellentesque, tellus sem mollis dui, in"),(98,"meurtre","vel sapien imperdiet ornare."),(99,"voiture volée","enim. Sed nulla ante, iaculis nec,"),(100,"viol","non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc");
