DROP TABLE `user`;

CREATE TABLE `user` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `id` mediumint,
  `login` TEXT default NULL,
  `password` TEXT default NULL,
  `first_name` varchar(255) default NULL,
  `last_name` varchar(255) default NULL,
  `role` varchar(255) default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `user` (`id`,`login`,`password`,`first_name`,`last_name`,`role`) VALUES (1,"magna.","blandit","Amery","Chavez","agent"),(2,"Morbi","libero.","Myra","James","scientist"),(3,"consectetuer","sociis","Iliana","Powell","chief"),(4,"lacus,","quis,","Olympia","Russell","chief"),(5,"a","Nulla","Shelley","Michael","chief"),(6,"dapibus","enim.","Caleb","Kent","chief"),(7,"scelerisque","vitae","Carly","Sims","scientist"),(8,"eu","quis","Aristotle","Stark","admin"),(9,"sed,","mi","Yasir","Christian","agent"),(10,"et","tincidunt.","Quinn","Sanford","scientist");
INSERT INTO `user` (`id`,`login`,`password`,`first_name`,`last_name`,`role`) VALUES (11,"blandit","nisi","Irene","Estes","admin"),(12,"enim","Nam","Wyoming","Cantu","scientist"),(13,"erat.","Pellentesque","Lilah","Smith","agent"),(14,"fringilla","lorem","Josiah","Harrison","chief"),(15,"urna.","non,","Audra","Mcgee",""),(16,"sit","volutpat","Graiden","Reyes","admin"),(17,"pede.","Cras","Rajah","Sosa",""),(18,"Lorem","In","Inez","Dalton","admin"),(19,"lacus.","a","Porter","Juarez","chief"),(20,"blandit.","fermentum","Britanney","Wallace","");
INSERT INTO `user` (`id`,`login`,`password`,`first_name`,`last_name`,`role`) VALUES (21,"arcu.","ac","Kareem","Petty","scientist"),(22,"Curabitur","luctus","Mikayla","Gross","scientist"),(23,"nisl.","Nullam","Chadwick","Wolf","agent"),(24,"malesuada","metus.","Chloe","Serrano",""),(25,"egestas","quis","Ashton","Hardy","agent"),(26,"sit","vestibulum,","Keane","Craig","admin"),(27,"posuere","ut","Lionel","Macdonald",""),(28,"turpis.","nec","Lacota","Pacheco","chief"),(29,"vestibulum","Donec","Vivian","Atkinson","chief"),(30,"ornare,","sit","Meghan","Cook","scientist");
INSERT INTO `user` (`id`,`login`,`password`,`first_name`,`last_name`,`role`) VALUES (31,"elit","mi.","Yuli","Witt","agent"),(32,"Cras","Morbi","Grant","Strickland","scientist"),(33,"Proin","Etiam","Ina","Noel","agent"),(34,"faucibus","malesuada","Gisela","Jensen","admin"),(35,"imperdiet","fringilla.","Giacomo","Whitley","agent"),(36,"lectus,","non,","Philip","Richardson",""),(37,"pede,","lectus,","Imelda","Howard","scientist"),(38,"nonummy","dictum.","Kane","Wilson","admin"),(39,"mauris,","varius","Vanna","Daniel","scientist"),(40,"ullamcorper.","tempus","Melanie","Bowman","");
INSERT INTO `user` (`id`,`login`,`password`,`first_name`,`last_name`,`role`) VALUES (41,"mus.","nisi.","Eagan","Patrick","agent"),(42,"Suspendisse","at","Grant","Kramer",""),(43,"Nulla","malesuada","Troy","Caldwell",""),(44,"nec","ligula","Colleen","Nolan","scientist"),(45,"Cras","at","Bianca","Gay","admin"),(46,"fringilla","magna","Sopoline","Patton","scientist"),(47,"tellus,","scelerisque","Jael","Wooten","scientist"),(48,"dolor.","a,","Jillian","Rice","scientist"),(49,"dictum","ultricies","Rae","Roach","scientist"),(50,"nec,","pede,","Imelda","Glenn","agent");
INSERT INTO `user` (`id`,`login`,`password`,`first_name`,`last_name`,`role`) VALUES (51,"Aliquam","convallis","Mary","Santos","scientist"),(52,"molestie","sem","Daria","Lott","admin"),(53,"massa.","non,","Francesca","Chaney",""),(54,"lorem","turpis","Zenia","Hickman","scientist"),(55,"neque","adipiscing","Sydney","Obrien","chief"),(56,"ut","ante,","Morgan","Mcbride","admin"),(57,"Praesent","eleifend.","Martha","Newton",""),(58,"quis","malesuada","Jescie","Richardson","agent"),(59,"dui,","nulla","Kamal","Hendricks","chief"),(60,"at,","Aenean","Lars","Mcintyre","chief");
INSERT INTO `user` (`id`,`login`,`password`,`first_name`,`last_name`,`role`) VALUES (61,"turpis.","sit","Keith","Crosby","chief"),(62,"fringilla","lorem","Denise","Williamson","scientist"),(63,"sit","nulla.","Ross","Mcdowell","admin"),(64,"vel","sed","Adara","Knapp","agent"),(65,"euismod","lacus.","Palmer","Turner","chief"),(66,"lacinia","adipiscing","Raven","Dotson","chief"),(67,"convallis","erat","Amethyst","Holland","admin"),(68,"eget,","lorem","Whilemina","Cannon","admin"),(69,"massa.","erat","Abbot","Campbell","scientist"),(70,"molestie","molestie.","Zorita","Parrish","chief");
INSERT INTO `user` (`id`,`login`,`password`,`first_name`,`last_name`,`role`) VALUES (71,"mi","massa.","Ian","Hendricks","chief"),(72,"venenatis","nunc","Darius","Pena",""),(73,"Sed","ac","Urielle","Oliver",""),(74,"a,","eu","Jayme","Larsen","chief"),(75,"elementum","orci,","Lars","Curry","chief"),(76,"erat,","feugiat.","Jorden","Battle","chief"),(77,"neque.","parturient","Madaline","Simon",""),(78,"ac,","Nam","Kadeem","Santana",""),(79,"lorem","in","Callum","Mercado","admin"),(80,"mi","arcu.","Orlando","Mann","agent");
INSERT INTO `user` (`id`,`login`,`password`,`first_name`,`last_name`,`role`) VALUES (81,"tempus,","blandit","Kyle","Fox",""),(82,"porttitor","Donec","Josiah","Leach","chief"),(83,"felis,","Nullam","Caesar","Phelps","admin"),(84,"Integer","Mauris","Daphne","Moreno","chief"),(85,"convallis","risus.","Wing","Yates",""),(86,"lacus","sit","Uma","Mcdaniel",""),(87,"neque.","eu","Lydia","Pacheco","agent"),(88,"vitae","vulputate,","Karyn","Sweet","admin"),(89,"eget","orci.","Quentin","Stevenson","agent"),(90,"odio.","elit.","Marshall","Ruiz","agent");
INSERT INTO `user` (`id`,`login`,`password`,`first_name`,`last_name`,`role`) VALUES (91,"at","augue.","Alfonso","Robles","chief"),(92,"Fusce","Vivamus","Mannix","Blanchard","scientist"),(93,"scelerisque","sed","Michael","Watson","scientist"),(94,"nulla","luctus","Cleo","Wilkins",""),(95,"nec","Maecenas","Dexter","Alston","scientist"),(96,"Aliquam","Integer","Raja","Howell","scientist"),(97,"Cum","quis,","Madison","Trujillo",""),(98,"Quisque","Cum","Leonard","Gibbs","scientist"),(99,"pede.","vel,","Judah","Haynes","admin"),(100,"porttitor","enim.","Noelle","Lowery","");
