DROP TABLE `vehicule`;

CREATE TABLE `vehicule` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `id` mediumint,
  `name` TEXT default NULL,
  `brand` varchar(255) default NULL,
  `color` varchar(255) default NULL,
  `license_plate` varchar(255),
  `comment` TEXT default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `vehicule` (`id`,`name`,`brand`,`color`,`license_plate`,`comment`) VALUES (1,"lorem ipsum sodales","Tata Motors","green","C1R 0O3","orci. Phasellus dapibus quam quis diam. Pellentesque"),(2,"quis","Citroën","yellow","N3B 0P2","mus. Aenean eget"),(3,"porttitor","BMW","yellow","S9G 0V9","vitae, sodales at, velit. Pellentesque ultricies dignissim lacus."),(4,"luctus et","Lincoln","violet","H1P 7P6","lobortis tellus justo sit"),(5,"arcu","Seat","blue","A6D 8N3","elementum sem, vitae aliquam"),(6,"felis purus","Maruti Suzuki","yellow","R8P 9W3","tristique pharetra. Quisque ac libero nec ligula consectetuer"),(7,"dolor.","Isuzu","violet","R3J 0Q9","enim nisl elementum purus, accumsan interdum libero dui"),(8,"risus. Donec","Seat","blue","A2E 1X6","velit eget laoreet posuere, enim nisl elementum purus,"),(9,"nibh lacinia orci,","Fiat","orange","B2Q 5M0","Vivamus nibh"),(10,"vel nisl.","Isuzu","red","H7P 4D9","Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros");
INSERT INTO `vehicule` (`id`,`name`,`brand`,`color`,`license_plate`,`comment`) VALUES (11,"Nullam lobortis","Jeep","red","X6U 8L5","Nunc mauris."),(12,"elit,","Buick","red","S6L 6X9","tincidunt nibh. Phasellus nulla. Integer vulputate, risus"),(13,"orci,","Subaru","red","H8N 0J4","ullamcorper viverra."),(14,"imperdiet non,","Volkswagen","yellow","A9K 0I0","Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor,"),(15,"eu arcu. Morbi","Porsche","red","C2S 2Y1","mollis. Phasellus"),(16,"dui augue eu","Skoda","yellow","Z0L 4C2","ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare"),(17,"arcu. Vivamus sit","Chrysler","violet","M3S 2T3","sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie"),(18,"metus.","Hyundai Motors","blue","S7P 8Y2","Suspendisse commodo tincidunt nibh."),(19,"mi enim,","Daimler","indigo","F8N 2Q5","dolor. Fusce mi lorem,"),(20,"eleifend, nunc risus","Chrysler","green","U9N 5C7","dui lectus rutrum urna, nec luctus");
INSERT INTO `vehicule` (`id`,`name`,`brand`,`color`,`license_plate`,`comment`) VALUES (21,"amet","Mahindra and Mahindra","blue","M3R 1M9","luctus felis purus ac tellus. Suspendisse sed dolor."),(22,"purus, in molestie","Daihatsu","green","Y0E 0S4","arcu. Vestibulum"),(23,"Curabitur consequat,","Jeep","red","I5H 1Z3","convallis, ante"),(24,"Duis mi","RAM Trucks","blue","X5D 1V8","luctus ut, pellentesque eget, dictum placerat,"),(25,"euismod ac,","Lincoln","violet","C1J 4L3","Aliquam auctor, velit eget laoreet"),(26,"lacinia","Daimler","violet","J8U 2G0","non ante"),(27,"sem mollis dui,","Buick","indigo","H6H 6U3","eget metus. In nec orci."),(28,"ac metus","Mahindra and Mahindra","blue","N9T 9P0","sed dolor. Fusce"),(29,"libero dui nec","Dongfeng Motor","violet","K5N 3H5","ridiculus mus. Aenean"),(30,"Phasellus at","Subaru","violet","T2K 5C0","a, aliquet vel, vulputate eu, odio.");
INSERT INTO `vehicule` (`id`,`name`,`brand`,`color`,`license_plate`,`comment`) VALUES (31,"Proin velit.","Mahindra and Mahindra","violet","K2D 0A1","magna et ipsum cursus"),(32,"auctor,","Citroën","violet","M8W 5K9","sit"),(33,"Pellentesque ultricies dignissim","Dodge","yellow","T8Q 5N4","enim"),(34,"sollicitudin","Seat","yellow","J7V 0S5","faucibus leo, in lobortis tellus justo sit amet nulla."),(35,"at auctor","Mitsubishi Motors","red","G5R 2G1","mauris id"),(36,"dui, nec tempus","Porsche","yellow","U5P 4T1","mauris sit amet lorem semper auctor. Mauris vel turpis."),(37,"ipsum. Suspendisse sagittis.","Kenworth","orange","A1H 6C9","amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet"),(38,"dapibus rutrum,","Isuzu","indigo","A7D 2B3","Nulla interdum."),(39,"ipsum sodales","General Motors","blue","M0E 3R3","justo faucibus lectus, a sollicitudin orci sem eget"),(40,"lorem, vehicula","Daimler","yellow","Z7T 2H7","sapien imperdiet");
INSERT INTO `vehicule` (`id`,`name`,`brand`,`color`,`license_plate`,`comment`) VALUES (41,"ligula. Aenean","Kia Motors","indigo","O7F 4O6","sagittis semper. Nam tempor diam dictum sapien. Aenean massa."),(42,"id magna et","Dodge","violet","T5Q 1W3","mauris. Integer"),(43,"non,","Chrysler","yellow","G9O 4Y3","ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices,"),(44,"massa.","MINI","indigo","W4W 0C5","scelerisque sed, sapien. Nunc pulvinar arcu"),(45,"turpis nec","Smart","red","X5J 0S1","magna. Suspendisse tristique neque venenatis"),(46,"in magna. Phasellus","Mahindra and Mahindra","orange","G6D 2B7","tellus id nunc interdum feugiat."),(47,"est, vitae","Maruti Suzuki","yellow","I5M 3E7","nunc interdum feugiat. Sed nec"),(48,"sollicitudin commodo ipsum.","Ferrari","red","U4H 2B8","purus sapien, gravida non, sollicitudin"),(49,"Sed","Isuzu","violet","J4S 2L6","ultrices iaculis odio. Nam interdum enim non"),(50,"orci lacus vestibulum","Isuzu","blue","H4Q 5N9","vestibulum lorem, sit");
INSERT INTO `vehicule` (`id`,`name`,`brand`,`color`,`license_plate`,`comment`) VALUES (51,"netus et","Daihatsu","blue","B5Y 9H0","suscipit nonummy. Fusce fermentum"),(52,"quis,","Hyundai Motors","red","U8Y 6H3","ac orci. Ut semper"),(53,"elementum,","Subaru","red","G7M 8V6","sed"),(54,"mauris blandit","Volvo","red","Q2B 7U6","lacinia vitae,"),(55,"conubia nostra, per","Mahindra and Mahindra","orange","O7Q 5C2","malesuada augue"),(56,"adipiscing lobortis risus.","Acura","red","P2W 6X4","augue scelerisque"),(57,"Proin vel nisl.","Lexus","violet","M8P 0K3","scelerisque mollis. Phasellus libero mauris, aliquam"),(58,"neque sed","Buick","violet","U3D 3G0","dolor."),(59,"hendrerit. Donec","Volvo","indigo","Z0D 3O2","dui. Cum sociis natoque penatibus et"),(60,"risus","General Motors","blue","T6H 9K8","Sed");
INSERT INTO `vehicule` (`id`,`name`,`brand`,`color`,`license_plate`,`comment`) VALUES (61,"quam,","Smart","orange","D6A 6C2","elit. Nulla facilisi. Sed neque. Sed eget"),(62,"porttitor eros nec","Jeep","indigo","L3D 5Q7","libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus"),(63,"auctor ullamcorper,","Audi","orange","D1B 3D9","neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris"),(64,"hendrerit consectetuer,","Maruti Suzuki","red","J3D 6L9","dis parturient montes, nascetur"),(65,"purus.","Skoda","red","T2Z 5G1","egestas, urna"),(66,"orci luctus","Mazda","blue","X8H 5S3","mauris id sapien. Cras dolor dolor, tempus non, lacinia at,"),(67,"convallis ligula. Donec","Smart","violet","G6F 9L7","Fusce"),(68,"leo,","Lincoln","yellow","H7S 2Z0","sapien. Aenean massa."),(69,"tellus. Nunc","Nissan","violet","G8Z 6I0","est tempor bibendum. Donec felis orci, adipiscing non,"),(70,"ipsum dolor","Mercedes-Benz","yellow","P8L 6E9","tortor nibh sit amet orci. Ut sagittis");
INSERT INTO `vehicule` (`id`,`name`,`brand`,`color`,`license_plate`,`comment`) VALUES (71,"penatibus et magnis","Chrysler","yellow","B1L 6E3","diam. Sed diam lorem, auctor quis, tristique ac,"),(72,"Nam","Volkswagen","indigo","C6J 8L9","odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus."),(73,"Sed eu eros.","Mitsubishi Motors","green","W7M 2Q7","facilisis. Suspendisse"),(74,"Etiam","Dodge","blue","N0U 3F2","Proin dolor. Nulla semper tellus id nunc interdum feugiat."),(75,"Sed","Volkswagen","orange","Y8T 6Y9","orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam"),(76,"blandit congue.","Subaru","red","O6J 6V2","Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper"),(77,"pretium","Acura","yellow","T1Q 0G0","ridiculus mus. Donec dignissim magna a tortor. Nunc"),(78,"vitae odio sagittis","Infiniti","violet","D6G 4I3","Pellentesque ultricies dignissim lacus. Aliquam rutrum"),(79,"dis parturient","Vauxhall","red","A2H 8Z5","enim, condimentum eget, volutpat ornare, facilisis"),(80,"lorem ac","Hyundai Motors","green","T5L 5X8","enim commodo hendrerit. Donec");
INSERT INTO `vehicule` (`id`,`name`,`brand`,`color`,`license_plate`,`comment`) VALUES (81,"natoque","RAM Trucks","red","G2J 4B8","Vivamus sit"),(82,"ridiculus","Mahindra and Mahindra","yellow","S0X 5X0","montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique"),(83,"Aliquam gravida","Infiniti","yellow","W5N 7I8","Integer in magna. Phasellus dolor elit, pellentesque a, facilisis"),(84,"ligula. Donec","Renault","violet","M5B 4B1","nostra, per inceptos hymenaeos. Mauris ut quam"),(85,"hendrerit consectetuer,","Mazda","blue","Z3U 0S3","Pellentesque ultricies"),(86,"nibh","Smart","yellow","U3Z 9R4","amet, risus. Donec nibh enim, gravida sit amet, dapibus id,"),(87,"dictum. Phasellus in","Acura","red","T1B 4U8","egestas. Aliquam nec enim. Nunc ut erat."),(88,"dui, semper","Suzuki","violet","X9U 1T6","lacus, varius et, euismod et, commodo at, libero."),(89,"lorem ut","Daihatsu","red","B4T 4E9","metus eu erat"),(90,"sem. Nulla interdum.","Kia Motors","orange","U9A 2L1","Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor");
INSERT INTO `vehicule` (`id`,`name`,`brand`,`color`,`license_plate`,`comment`) VALUES (91,"Nullam vitae","Volvo","indigo","H9K 7M0","dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec"),(92,"aliquam eros turpis","Porsche","indigo","M6K 4T8","egestas a, scelerisque sed, sapien. Nunc"),(93,"massa. Suspendisse eleifend.","Cadillac","violet","F7V 9D0","luctus vulputate, nisi sem semper erat,"),(94,"quis lectus. Nullam","Jeep","orange","J9C 1F7","mauris eu elit. Nulla facilisi. Sed neque. Sed"),(95,"vel","Seat","violet","Y1Y 4T9","iaculis aliquet diam."),(96,"pretium","Volvo","blue","Q2W 2U8","luctus"),(97,"ipsum.","Honda","green","A5B 3W1","sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing"),(98,"pellentesque eget,","Volvo","indigo","B3I 3L7","fringilla. Donec"),(99,"Vestibulum ante","Volkswagen","indigo","A0K 0F7","id sapien. Cras"),(100,"velit. Cras lorem","Acura","red","D4J 5A9","pharetra sed, hendrerit a, arcu. Sed et libero. Proin");
