DROP TABLE `weapon`;

CREATE TABLE `weapon` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `id` mediumint,
  `model` varchar(255) default NULL,
  `serial` varchar(255),
  `comment` TEXT default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `weapon` (`id`,`model`,`serial`,`comment`) VALUES (1," Mauser C96  	","E4Z 5Q3","porta elit, a feugiat tellus"),(2,"	 Breda Model 37  ","Y2D 8F9","ac mattis semper, dui lectus rutrum urna, nec luctus felis"),(3,"   FM 24/29  	","Y4J 5F2","tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id,"),(4," Browning ","Y4X 6S2","velit egestas"),(5," Vickers-Berthier ","X6C 7A8","Cras pellentesque. Sed dictum. Proin eget"),(6," Lee-Enfield No. 4","J3F 2A9","mauris ipsum porta elit, a feugiat tellus lorem"),(7," MP 35  ","Q7D 1O8","accumsan convallis, ante lectus convallis est, vitae sodales nisi magna"),(8," Danuvia 39M  	","F9V 4P5","sit amet metus. Aliquam"),(9," Enfield No. 2 ","T0G 5U3","tempor lorem, eget"),(10," Kg m/40  ","G1B 3T9","sed dolor. Fusce");
INSERT INTO `weapon` (`id`,`model`,`serial`,`comment`) VALUES (11,"	 Bren  	","N4N 5A7","convallis in, cursus et, eros. Proin ultrices. Duis volutpat"),(12," Sten  	Gun  	","T1Y 5W5","egestas nunc sed libero. Proin sed turpis nec mauris"),(13," Carcano M1938  	","F0X 7S2","velit. Sed malesuada augue ut lacus."),(14," Carcano M1938  	","M5P 7B3","ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor"),(15,"	 Colt M1917  	","U1O 3I2","bibendum. Donec"),(16," Vickers-Berthier ","D2U 1S9","erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum"),(17," 	 SG-43 Goryunov  	","Y2R 9G1","neque. Nullam ut nisi a odio"),(18,"	 Sauer 38H ","W3V 0M7","Sed malesuada augue ut lacus. Nulla"),(19,"  	 Austen  	","X8T 0Z6","nulla. Integer vulputate, risus a ultricies adipiscing, enim"),(20," Vis  	","K9C 3H8","Vivamus");
INSERT INTO `weapon` (`id`,`model`,`serial`,`comment`) VALUES (21," Mauser Kar98k  	","Y0H 7K1","iaculis quis, pede."),(22," Browning M1919  	","X4O 3X0","aliquet odio. Etiam ligula"),(23," MG 42  ","C4A 3N2","rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus"),(24," MG 08  	","K7O 0S4","sit amet ante. Vivamus non lorem vitae odio"),(25," FN M1910  	","R9D 6Q4","pharetra ut, pharetra sed, hendrerit a, arcu. Sed"),(26," MG 34  	","C0Y 5E2","senectus et netus et malesuada fames ac turpis egestas."),(27,"	 Hanyang Type 88  ","H1C 5R2","non, vestibulum nec, euismod in, dolor. Fusce"),(28," 	 SG-43 Goryunov  	","P5T 6C4","eros"),(29," DShK M1938  ","U4D 9L8","nisi. Aenean eget metus. In nec orci. Donec nibh."),(30," Beretta M1938  	","B3S 9S7","Praesent");
INSERT INTO `weapon` (`id`,`model`,`serial`,`comment`) VALUES (31," Danuvia 39M  	","K1K 5T9","in, hendrerit consectetuer, cursus et, magna. Praesent interdum"),(32," PPS  	","E9H 2X9","elit elit fermentum risus, at fringilla purus mauris"),(33,"","S5R 4I4","auctor vitae, aliquet nec, imperdiet nec, leo. Morbi"),(34,"   FM 24/29  	","U7K 4V4","tincidunt, nunc ac mattis ornare,"),(35," MP 40  ","T6P 1K3","feugiat nec, diam. Duis"),(36," ZK-383  ","M4H 0F3","gravida sagittis. Duis"),(37,"	 M1 Garand  ","L7J 7G8","eget magna. Suspendisse tristique neque venenatis"),(38," 	 Parabellum P08 'Luger' ","S4S 2N5","non, bibendum sed, est. Nunc laoreet lectus quis"),(39," MG 08  	","C7H 5E5","morbi tristique senectus"),(40," Springfield M1903  	","J6A 0S2","bibendum ullamcorper. Duis cursus, diam at");
INSERT INTO `weapon` (`id`,`model`,`serial`,`comment`) VALUES (41," Beretta M1934  	","X6T 1Z8","eros turpis"),(42,"	 KP/-31  ","X2A 6M0","Donec porttitor tellus non"),(43,"	 Hanyang Type 88  ","L9I 3N3","montes,"),(44,"	 M3 'Grease Gun' ","H0Y 2O7","dui. Cras pellentesque. Sed dictum. Proin eget"),(45," Madsen  	","E9T 6Z8","lobortis. Class aptent taciti sociosqu ad litora torquent per"),(46," PPSh-41  ","B9L 8B7","facilisis. Suspendisse commodo tincidunt nibh. Phasellus"),(47," Gewehr 41  	","C1C 1T5","tempor erat neque non quam. Pellentesque"),(48," Browning M1917  	","E9B 0T5","arcu. Sed et"),(49,"	 Tokarev SVT-40  ","F1S 2V4","erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula."),(50," Winchester Model 1912 ","R6X 5N6","arcu. Nunc mauris. Morbi non sapien");
INSERT INTO `weapon` (`id`,`model`,`serial`,`comment`) VALUES (51," Danuvia 39M  	","W3Y 3M8","elit. Etiam laoreet, libero et tristique pellentesque, tellus"),(52," Browning M2  	","H5K 9C0","gravida mauris ut mi. Duis risus odio, auctor"),(53," Carcano M1891  ","C5T 6G2","ac"),(54,"	 Hanyang Type 88  ","S0V 3I2","Cras dictum ultricies ligula. Nullam enim."),(55," MG 15  ","R0G 6R7","elementum, dui quis"),(56,"	 Tokarev SVT-40  ","S2C 8P1","posuere at, velit. Cras lorem lorem,"),(57,"	 Berthier  	","V1W 8P7","Nunc mauris sapien, cursus"),(58," ZH-29  	","I4U 7G1","sodales nisi magna sed dui."),(59,"	 KP/-31  ","T7C 3T2","Maecenas mi felis, adipiscing fringilla,"),(60,"	 Thompson  	","S3Y 8I8","aliquet vel, vulputate eu, odio. Phasellus at augue id ante");
INSERT INTO `weapon` (`id`,`model`,`serial`,`comment`) VALUES (61,"	 Nagant M1895 ","N8W 2T9","varius et, euismod et, commodo at, libero."),(62," Vickers-Berthier ","Q6O 0F9","Etiam"),(63," Walther P38  	","P6S 6N1","cursus in, hendrerit consectetuer,"),(64,"	 Berthier  	","G3G 0V4","ornare sagittis felis. Donec tempor, est ac"),(65," 	 Panzerbüchse 38","X5R 6L5","blandit congue. In scelerisque scelerisque"),(66," ZK-383  ","R5Z 4T8","Mauris"),(67," Bodeo M1889  	","I9Z 1E4","litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut"),(68,"	 Tokarev SVT-40  ","Z8W 7S7","et netus et malesuada"),(69," Browning M1917  	","M4X 7J0","ligula elit, pretium et, rutrum non, hendrerit id,"),(70," FNAB-43  	","Z6K 0M5","egestas lacinia. Sed");
INSERT INTO `weapon` (`id`,`model`,`serial`,`comment`) VALUES (71," PPS  	","Q8E 3I8","rutrum urna, nec luctus felis purus ac"),(72," PPSh-41  ","L8M 5V3","eu lacus. Quisque imperdiet, erat"),(73," Sten  	Gun  	","A5N 3X5","commodo hendrerit. Donec porttitor tellus non magna. Nam ligula"),(74,"	 Breda Model 37  ","Q5Z 3K6","lorem, sit amet ultricies sem magna nec quam."),(75," Solothurn S-18/100  	","K6C 0X1","dignissim. Maecenas ornare"),(76,"  MP 34  	","H8A 3W7","tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus."),(77," Steyr M1912  	","L7Y 8Z5","magna"),(78," Mannlicher-Schönauer","J6U 8I6","amet risus. Donec egestas. Aliquam nec enim."),(79," 	 M4 Survival  	","O0T 9T5","pede et risus. Quisque"),(80," Mosin-Nagant ","V5H 5D3","est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia");
INSERT INTO `weapon` (`id`,`model`,`serial`,`comment`) VALUES (81," ZB vz. 24  	","U8K 2D1","sit amet massa. Quisque"),(82,"	 Hanyang Type 88  ","X9C 4G8","massa. Integer vitae nibh."),(83,"	 Steyr-Mannlicher ","O6U 9N3","dolor sit"),(84," 	 FG 42  ","X4Z 3L8","Suspendisse sagittis. Nullam"),(85," Walther P38  	","M3S 0G9","ut aliquam iaculis, lacus pede"),(86," Gewehr 98  	","O4B 2B2","risus."),(87," 	 PPD  	","Z8M 2D3","commodo auctor velit."),(88,"	 TZ-45  	","U0U 5X9","consectetuer adipiscing elit."),(89," 	 Johnson M1941    ","U5K 5A3","Donec"),(90," FNAB-43  	","J8V 3Z5","et, euismod et,");
INSERT INTO `weapon` (`id`,`model`,`serial`,`comment`) VALUES (91," Steyr M1912  	","C0V 0C0","at arcu. Vestibulum ante ipsum primis in faucibus orci"),(92," Beretta M1934  	","M5T 1V7","ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla."),(93," 	 Lewis  ","Q9D 5X7","Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae"),(94,"  	 Lahti-Saloranta M/26","J8J 1H7","fames ac turpis egestas. Fusce aliquet magna a"),(95,"	 KE-7  	","Y7H 5O9","ipsum. Suspendisse non leo. Vivamus"),(96," 	 Parabellum P08 'Luger' ","M8F 7Z6","per inceptos"),(97," Browning M1917  	","F5J 5W8","montes, nascetur ridiculus mus. Donec"),(98," Winchester Model 1897  	","H6J 1D6","Nunc"),(99,"	 KP/-31  ","J8T 0Y3","in faucibus orci luctus et"),(100," Madsen  	","L2B 0X0","in, cursus et, eros.");
